# Generated by Django 3.2.3 on 2021-05-20 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brooklyn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='ProjectName',
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 20, 14, 17, 81617)),
        ),
    ]
