# Generated by Django 3.1.1 on 2021-05-21 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brooklyn', '0002_auto_20210520_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectobject',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 13, 2, 34, 691796)),
        ),
    ]
