# Generated by Django 3.1.1 on 2021-05-24 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brooklyn', '0004_auto_20210524_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectobject',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 18, 42, 4, 696296, tzinfo=utc)),
        ),
    ]
