# Generated by Django 3.1.1 on 2021-05-24 19:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brooklyn', '0005_auto_20210524_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 19, 8, 47, 331016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brooklyn.project'),
        ),
    ]
