# Generated by Django 3.1.1 on 2021-05-30 08:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brooklyn', '0007_auto_20210525_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Description',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Field1Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='Field2Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='Field3Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='Field4Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='Field5Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 8, 57, 50, 638552, tzinfo=utc)),
        ),
    ]
